# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sourav Sahoo
email: "sahoosourav1996@gmail.com"
description: >
  Ambitious and eager full stack web developer. Avid open source contributor. Fascinated by Algorithm and Data Structures. Love building things through different technologies.

about_me: >
  I am a Computer Science Student at NIT Hamirpur. I like to contribute in open source. I have done Google Summer of Code 2018 in Public Lab. I am also currently mentoring for Google Code in in the same organisation. I also like to participate in coding competitions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://souravirus.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/souravsahoo"
github_link: "https://www.github.com/souravirus"
twitter_username: "sahoosourav1996"
google_analytics_id: ''
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
